# Shipment Data Quality Report

Report schema validation, row-level failures and acceptance counts. Every rule has an explicit checked-record count; unavailable fields cannot silently pass.

## 1. Load the actual input

In [1]:
import sys
from pathlib import Path

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "config/config.yaml").is_file())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
import pandas as pd
from IPython.display import display

from src.analytics import build_tables, kpis
from src.etl.extract import DataExtractor
from src.etl.transform import DataTransformer
from src.etl.validate import DataValidator
from src.utils.config_loader import ConfigLoader

raw = DataExtractor(ConfigLoader()).extract()
validation = DataValidator().validate(raw)
assert validation.report["rejected_records"] == 0, "Inspect quality report before analyzing rejected data"
df = DataTransformer().transform(validation.accepted)
tables = build_tables(df)
metrics = kpis(df)
print(f"{len(df):,} shipments | {df.dominant_mode.nunique()} observed dominant modes")

20,000 shipments | 3 observed dominant modes

All 18 source columns are required. Units and categorical values follow the repository data dictionary.

## 2. Acceptance and rejection counts

In [2]:
summary = {
    key: validation.report[key]
    for key in [
        "schema_valid",
        "input_records",
        "accepted_records",
        "rejected_records",
        "rejection_pct",
        "rules_evaluated",
    ]
}
display(pd.DataFrame([summary]))

   schema_valid  input_records  ...  rejection_pct  rules_evaluated
0          True          20000  ...            0.0               23

[1 rows x 6 columns]

The pipeline defaults to a zero-rejection quality gate. Any rejected records are quarantined and the pipeline fails unless an explicit rejection threshold is configured.

## 3. Rules evaluated

In [3]:
rules = pd.DataFrame(validation.report["rules"]).T
rules["passed_records"] = rules.checked_records - rules.failed_records
display(rules)

                                    failed_records  ...  passed_records
missing_or_empty_text                            0  ...           20000
invalid_or_nonfinite_numeric                     0  ...           20000
noninteger_planned_duration_hours                0  ...           20000
noninteger_actual_duration_hours                 0  ...           20000
noninteger_risk_flag                             0  ...           20000
noninteger_total_legs                            0  ...           20000
nonpositive_weight_tons                          0  ...           20000
nonpositive_total_distance_km                    0  ...           20000
nonpositive_planned_duration_hours               0  ...           20000
nonpositive_actual_duration_hours                0  ...           20000
nonpositive_total_legs                           0  ...           20000
negative_declared_value_usd                      0  ...           20000
negative_total_fuel_cost_usd                     0  ...           20000
negative_avg_leg_delay_minutes                   0  ...           20000
negative_weather_severity_avg                    0  ...           20000
invalid_maintenance_score                        0  ...           20000
invalid_risk_flag                                0  ...           20000
invalid_transport_mode                           0  ...           20000
invalid_status                                   0  ...           20000
invalid_priority                                 0  ...           20000
status_duration_mismatch                         0  ...           20000
exact_duplicate                                  0  ...           20000
conflicting_shipment_id                          0  ...           20000

[23 rows x 3 columns]

A row may fail multiple rules, so adding rule failures is not the number of rejected shipments. Missing columns fail schema validation before these rules run.

## 4. Key and label consistency

In [4]:
print("Duplicate shipment IDs:", int(raw.shipment_id.duplicated().sum()))
expected_status = raw.actual_duration_hours.le(raw.planned_duration_hours).map(
    {True: "On-Time", False: "Delayed"}
)
print("Status/duration disagreements:", int(raw.status.ne(expected_status).sum()))
print("Nonpositive distances:", int(raw.total_distance_km.le(0).sum()))
print("Nonpositive weights:", int(raw.weight_tons.le(0).sum()))

Duplicate shipment IDs: 0
Status/duration disagreements: 0
Nonpositive distances: 0
Nonpositive weights: 0

Status is verified against the planned and actual durations. Cost ratios are only computed after distance and weight pass positive-value checks.

## 5. Persisted report

In [5]:
import json

report_path = ROOT / "outputs/data_quality_report.json"
if report_path.exists():
    report = json.loads(report_path.read_text())
    assert report["input_records"] == len(raw)
    display(pd.DataFrame([{k: report[k] for k in summary}]))
else:
    print("Run python run_full_pipeline.py to publish the quality report and quarantine file.")

   schema_valid  input_records  ...  rejection_pct  rules_evaluated
0          True          20000  ...            0.0               23

[1 rows x 6 columns]

The repository does not document an upstream collection process. Passing these implemented rules does not establish source authenticity or production readiness.